[build]
  publish = "dist"
  command = "tsc -b && vite build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Ottimizzazioni build
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

# Variabili ambiente per produzione
[context.production.environment]
  VITE_APP_NAME = "RD Group"
  VITE_COMPANY_PHONE = "+39 057 318 74672"
  VITE_COMPANY_EMAIL = "rdautosrlpistoia@gmail.com"
  VITE_SITE_URL = "https://rdgroup.netlify.app"
  VITE_ENABLE_ANALYTICS = "true"

# Variabili per staging (branch develop)
[context.deploy-preview.environment]
  VITE_APP_NAME = "RD Group - Preview"
  VITE_ENABLE_ANALYTICS = "false"

# Headers per performance e sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    # Sicurezza
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Cache base
    Cache-Control = "public, max-age=3600"

# Headers specifici per immagini
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers per assets statici
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers per manifest e serviceWorker
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirect per SEO e UX
[[redirects]]
  from = "/sedi"
  to = "/#sedi"
  status = 301

[[redirects]]
  from = "/contatti"
  to = "/#contatti"
  status = 301

[[redirects]]
  from = "/servizi"
  to = "/#servizi"
  status = 301

[[redirects]]
  from = "/chi-siamo"
  to = "/#chi-siamo"
  status = 301

# Redirect www to non-www (quando hai il dominio)
[[redirects]]
  from = "https://www.rdgroup.it/*"
  to = "https://rdgroup.it/:splat"
  status = 301
  force = true

# Gestione SPA routing (DEVE essere ultimo!)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurazione forms
[forms]
  [forms.settings]
    spam_filter = true